name: build-virac

on:
  push:
    tags:
      - '*'
    branches:
      - '*'

jobs:


  ubuntu:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - name: Install Compilers and Git
        run: apt-get update && apt-get install -y git build-essential

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install Miniconda
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          python-version: 3.9
          environment-file: virac.yml
          activate-environment: virac

      - name: Build PyORBIT3
        shell: bash -l {0}
        run: |
          conda info
          conda list -n virac          
          python -m pip install git+https://github.com/PyORBIT-Collaboration/PyORBIT3.git
          conda list

      - name: Build
        shell: bash -l {0}
        run: |
           .github/workflows/conda-build.sh

#      - name: Corrector Test
#        run: |
#           .github/workflows/corrector-test.sh
#
#      - name: Previous PVs Test
#        run: |
#           .github/workflows/pv-test.sh
#
#      - name: Print Versions
#        run: |
#           .github/workflows/conda-versions.sh
