name: build-virac

on:
  push:
    tags:
      - '*'
    branches:
      - '*'

jobs:


  ubuntu:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Compilers and Git
        run: apt-get update && apt-get install -y git build-essential

      # Install Miniconda
      - name: Setup Miniconda
        uses: goanpeca/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          auto-update-conda: true
          python-version: 3.9
          environment-file: virac.yml
          activate-environment: virac

      - name: Build PyORBIT3
        run: pip install git+https://github.com/PyORBIT-Collaboration/PyORBIT3.git

      - name: Build
        run: |
           git config --global --add safe.directory /__w/virtual-accelerator/virtual-accelerator
           .github/workflows/conda-build.sh

#      - name: Corrector Test
#        run: |
#           .github/workflows/corrector-test.sh
#
#      - name: Previous PVs Test
#        run: |
#           .github/workflows/pv-test.sh
#
#      - name: Print Versions
#        run: |
#           .github/workflows/conda-versions.sh
